name: Release MFE
description: An action to deploy an MFE to AWS S3

inputs:
  mfe_name:
    required: true
  cloudfront_url:
    required: true
  lambda_url:
    required: true
  key_id:
    required: true
  access_key:
    required: true
  s3_mfes:
    required: true
  cloudfront_id:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up pnpm
      uses: ./.github/actions/pnpm-setup

    - name: Build for AWS
      env:
        CLOUDFRONT_URL: ${{ inputs.cloudfront_url }}
        LAMBDA_URL: ${{ inputs.lambda_url }}
      shell: bash
      run: pnpm --filter @pi-lib/${{ inputs.mfe_name }}-mfe build:mfe

    - name: Configure AWS credentials
      shell: bash
      run: |
        aws configure set aws_access_key_id ${{ inputs.key_id }}
        aws configure set aws_secret_access_key ${{ inputs.access_key }}
        aws configure set default.region eu-west-2

    - name: Flush S3
      shell: bash
      run: |
        aws s3 rm s3://${{ inputs.s3_mfes }}/${{ inputs.mfe_name }} --recursive

    - name: Deploy to S3
      shell: bash
      run: |
        aws s3 sync src/apps/mfes/${{ inputs.mfe_name }}/dist s3://${{ inputs.s3_mfes }}/${{ inputs.mfe_name }} --acl public-read

    - name: Create CloudFront Invalidation
      shell: bash
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ inputs.cloudfront_id }} --paths "/*"
