name: Release Packages

on:
  pull_request:
    types:
      - closed
    branches: [main]

jobs:
  check-changes:
    name: Check for changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Changed files
        id: changes
        uses: tj-actions/changed-files@v39
        with:
          files: ./src/packages/**

    outputs:
      changed: ${{ steps.changes.outputs.any_changed }}

  release:
    name: Release packages to NPM
    needs: check-changes
    runs-on: ubuntu-latest
    if: needs.check-changes.outputs.changed == true && github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - uses: oleksiyrudenko/gha-git-credentials@v2.1
        with:
          global: true
          name: 'Lance Rael'
          email: '${{ secrets.PI_EMAIL }}'
          actor: 'LanceRael'
          token: '${{ secrets.PI_PUBLISH }}'

      - name: Set up pnpm
        uses: ./.github/actions/pnpm-setup

      - name: Build for vanilla dist
        env:
          CLOUDFRONT_URL: ${{ secrets.CLOUDFRONT_URL }}
        run: pnpm build

      - name: Setup beachball
        uses: ecraig12345/beachball-actions/install-beachball@v1

      - name: Publish packages
        run: npm run bb:publish -- -n ${{ secrets.PI_PUB }} -yes

  coverage:
    name: Code coverage report
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up pnpm
        uses: ./.github/actions/pnpm-setup

      - name: Build coverage report
        shell: bash
        run: pnpm test:cov

      - name: Coveralls
        uses: coverallsapp/github-action@v2
