name: Release Demo MFEs

on:
  pull_request:
    types:
      - closed
    branches: [main]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mfe-name: [chart-sandbox, candlestick-chart]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files_yaml: |
            mfes:
              - './src/mfes/${{ matrix.mfe-name }}/**'
            components:
              - './src/components/**'

      - name: List of changes
        shell: bash
        run:
          echo "Changes = ${{ steps.changed-files.outputs.all_changed_files }}" |
          echo "Has changed old = ${{ steps.changed-files.outputs.any_changed }}" |
          echo "Has changed = ${{ steps.changed-files.outputs.test_any_changed }}"

      - name: Set up pnpm
        if: steps.changed-files.outputs.test_any_changed == 'true'
        uses: ./.github/actions/pnpm-setup

      - name: Build for AWS
        if: steps.changed-files.outputs.test_any_changed == 'true'
        run: pnpm build

      - name: Deploy to S3 bucket
        if: steps.changed-files.outputs.test_any_changed == 'true'
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-2'
          SOURCE_DIR: 'src/mfes/${{ matrix.mfe-name }}/dist'
          DEST_DIR: '${{ matrix.mfe-name }}'

      - name: Configure AWS credentials
        if: steps.changed-files.outputs.test_any_changed == 'true'
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region eu-west-2

      - name: Create CloudFront Invalidation
        if: steps.changed-files.outputs.test_any_changed == 'true'
        run: |
          aws cloudfront create-invalidation --distribution-id E152JVQP5CZF23 --paths "/*"
