name: Release Chart Sandbox API

on:
  pull_request:
    types:
      - closed
    branches: [main]

jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for changes
        id: changed
        uses: ./.github/actions/check-changes
        with:
          files: ./src/apis/chart-sandbox-api/**

    outputs:
      folder_changed: ${{ steps.changes.outputs.changed }}

  release:
    needs: check-changes
    runs-on: ubuntu-latest
    if: needs.check-changes.outputs.changed == 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Set up pnpm
        uses: ./.github/actions/pnpm-setup

      - name: Release to AWS
        run: pnpm demo:sb:api-deploy
