name: Release Demo MFEs

on:
  pull_request:
    types:
      - closed
    branches: [main]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: ./src/mfes/chart-sandbox/**

      - name: List of changes
        shell: bash
        run: echo "Changes = ${{ steps.changed-files.outputs.all_changed_files }}"

      - name: Set up pnpm
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: ./.github/actions/pnpm-setup

      - name: Build for AWS
        if: steps.changed-files.outputs.any_changed == 'true'
        run: pnpm build

      - name: Deploy to S3 bucket
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2'
          SOURCE_DIR: 'src/mfes/chart-sandbox/dist'
