name: Release Demo MFEs

on:
  pull_request:
    types:
      - closed
    branches: [main]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mfe-name: [chart-sandbox, candlestick-chart]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: ./src/mfes/${{ matrix.mfe-name }}/**

      - name: List of changes
        shell: bash
        run: echo "Changes = ${{ steps.changed-files.outputs.all_changed_files }}"

      - name: Changed MFEs
        id: changed-mfes
        uses: tj-actions/changed-files@v37
        with:
          files: ./src/mfes/${{ matrix.mfe-name }}/**

      - name: Changed components
        id: changed-components
        uses: tj-actions/changed-files@v37
        with:
          files: ./src/components/**

      - name: List of changes
        shell: bash
        run: |
          echo "Changes = ${{steps.changed-mfes.outputs.all_changed_files}}, ${{ steps.changed-components.outputs.all_changed_files }}"

      - name: Evaluate condition and set output
        id: check-changes
        run: echo "has-changed=${{steps.changed-mfes.outputs.any_changed == 'true' || steps.changed-components.outputs.any_changed == 'true'}}" >> $GITHUB_OUTPUT

      - name: Set up pnpm
        if: steps.check-changes.outputs.has-changed == 'true'
        uses: ./.github/actions/pnpm-setup

      - name: Build for AWS
        if: steps.check-changes.outputs.has-changed == 'true'
        run: pnpm build

      - name: Deploy to S3 bucket
        if: steps.check-changes.outputs.has-changed == 'true'
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-2'
          SOURCE_DIR: 'src/mfes/${{ matrix.mfe-name }}/dist'
          DEST_DIR: '${{ matrix.mfe-name }}'

      - name: Configure AWS credentials
        if: steps.check-changes.outputs.has-changed == 'true'
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region eu-west-2

      - name: Create CloudFront Invalidation
        if: steps.check-changes.outputs.has-changed == 'true'
        run: |
          aws cloudfront create-invalidation --distribution-id E152JVQP5CZF23 --paths "/*"
