name: Release Demo MFEs

on:
  pull_request:
    types:
      - closed
    branches: [main]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mfe-name: [chart-sandbox, candlestick-chart]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Changed MFEs
        id: changed-mfes
        uses: tj-actions/changed-files@v35
        with:
          files: ./src/apps/mfes/${{ matrix.mfe-name }}/**

      - name: Changed packages
        id: changed-packages
        uses: tj-actions/changed-files@v35
        with:
          files: ./src/packages/**

      - name: Evaluate changes
        id: check-changes
        run: echo "has-changed=${{steps.changed-mfes.outputs.any_changed == 'true' || steps.changed-packages.outputs.any_changed == 'true'}}" >> $GITHUB_OUTPUT

      - name: Release the MFE
        if: steps.check-changes.outputs.has-changed == 'true'
        uses: ./.github/actions/release-mfe
        with:
          mfe_name: ${{ matrix.mfe-name }}
