name: Linting & Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up pnpm
        uses: ./.github/actions/pnpm-setup

      - name: Lint
        shell: bash
        run: pnpm lint

      - name: Test
        shell: bash
        run: pnpm test
